"""
render_chorus.py — SPECTRUM CHORUS media art piece.

10 skeleton figures arranged in a diagonal line, each animated at a different
dance intensity from MoMask's spectrum, blended through MiniGainNet against d=0.09
as common source. All ten walk in unison at the start, then diverge into their
individual intensities as GainNet's learned time-varying alpha releases each
figure to its own dance.

Aesthetic:
  - Turbo colormap per figure — cool blues at low intensity → warm oranges at high
  - Dark warm-cool gradient background (studio backdrop)
  - Slow camera orbit around the line's midpoint (~30°)
  - Bones drawn with 3-frame alpha-blended trail for soft motion blur
  - 1920x1080, 20fps, ~9.8s, silent

Reads as: a visible spectrum of motion, one identity fracturing into ten.

Prerequisites:
  - Blended joint npys for all 10 dance values must exist under
    outputs/pipeline_output/blended_d{value}.npy  (generated by chorus_prep.sh)

Usage:
    conda activate momask
    python render_chorus.py \
      --out outputs/media_art/spectrum_chorus.mp4 \
      --width 1920 --height 1080 --fps 20
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import matplotlib.animation as animation
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FFMpegWriter, FuncAnimation
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 — registers 3D projection

# HumanML3D t2m kinematic chain (22-joint SMPL body)
KINEMATIC_CHAIN = [
    [0, 2, 5, 8, 11],           # right leg
    [0, 1, 4, 7, 10],           # left leg
    [0, 3, 6, 9, 12, 15],       # spine → head
    [9, 14, 17, 19, 21],        # right arm
    [9, 13, 16, 18, 20],        # left arm
]

# 10 dance values — full spectrum from editing/ dirs
DANCE_VALUES = [0.09, 0.23, 0.28, 0.40, 0.42, 0.56, 0.70, 0.74, 0.97, 1.00]

NUM_FRAMES  = 196
NUM_JOINTS  = 22
LINE_SPACING = 1.4     # meters between characters along the diagonal
TRAIL_LENGTH = 3       # frames of motion-blur ghost
TRAIL_ALPHAS = [0.10, 0.18, 0.30]   # decreasing so oldest is faintest


def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("--blend-dir", default=str(Path.home() / "Downloads" / "momask-codes-main" / "identity_preservation" / "outputs" /
                                                "pipeline_output"))
    ap.add_argument("--out", default=str(Path.home() / "Downloads" / "momask-codes-main" / "identity_preservation" / "outputs" /
                                          "media_art" / "spectrum_chorus.mp4"))
    ap.add_argument("--width",  type=int, default=1920)
    ap.add_argument("--height", type=int, default=1080)
    ap.add_argument("--fps",    type=int, default=20)
    ap.add_argument("--dpi",    type=int, default=120)
    return ap.parse_args()


def load_all_motions(blend_dir: Path):
    """Load all 10 blended (T, 22, 3) joint arrays."""
    motions = []
    for d in DANCE_VALUES:
        path = blend_dir / f"blended_d{d:.2f}.npy"
        if not path.exists():
            raise SystemExit(f"[fatal] missing blended npy for d={d:.2f}: {path}\n"
                             f"        run chorus_prep.sh first.")
        arr = np.load(path).astype(np.float32)
        # Standardize (T, 22, 3)
        if arr.ndim == 4:
            arr = arr[0]
        assert arr.shape[1:] == (22, 3), f"unexpected shape {arr.shape} in {path}"
        # Pad/truncate to 196 frames
        T = NUM_FRAMES
        if arr.shape[0] > T:
            arr = arr[:T]
        elif arr.shape[0] < T:
            pad = np.repeat(arr[-1:], T - arr.shape[0], axis=0)
            arr = np.concatenate([arr, pad], axis=0)
        motions.append(arr)
    return motions


def line_positions(n: int, spacing: float) -> np.ndarray:
    """Diagonal line in XY plane, receding from front-left to back-right."""
    positions = np.zeros((n, 3), dtype=np.float32)
    for i in range(n):
        t = (i - (n - 1) / 2) / n              # centered around 0
        positions[i, 0] = t * spacing * n * 0.55   # X: left ↔ right
        positions[i, 1] = t * spacing * n * 0.40   # Y: front ↔ back (receding)
    return positions


def build_background(ax, radius: float):
    """Dark warm-cool gradient backdrop. Called once."""
    ax.set_facecolor("#0f0f18")
    ax.grid(False)
    ax.xaxis.pane.set_facecolor((0.06, 0.06, 0.10, 1.0))
    ax.yaxis.pane.set_facecolor((0.08, 0.08, 0.13, 1.0))
    ax.zaxis.pane.set_facecolor((0.05, 0.05, 0.08, 1.0))
    ax.xaxis.pane.set_edgecolor((0, 0, 0, 0))
    ax.yaxis.pane.set_edgecolor((0, 0, 0, 0))
    ax.zaxis.pane.set_edgecolor((0, 0, 0, 0))
    for axis in (ax.xaxis, ax.yaxis, ax.zaxis):
        axis.set_ticklabels([])
        axis.set_ticks([])
        axis.line.set_visible(False)


def render_character(ax, joints_frame: np.ndarray, offset: np.ndarray, color, alpha: float, linewidth: float):
    """Draw one skeleton figure at world position offset."""
    coords = joints_frame + offset  # (22, 3) in world
    for chain in KINEMATIC_CHAIN:
        ax.plot(
            coords[chain, 0], coords[chain, 1], coords[chain, 2],
            color=color, alpha=alpha, linewidth=linewidth, solid_capstyle="round",
        )
    ax.scatter(
        coords[:, 0], coords[:, 1], coords[:, 2],
        s=8, color=color, alpha=min(1.0, alpha * 1.2), edgecolors="none",
    )


def main() -> int:
    args = parse_args()
    blend_dir = Path(args.blend_dir)
    out_path  = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"[chorus] loading {len(DANCE_VALUES)} motions from {blend_dir}")
    motions   = load_all_motions(blend_dir)                          # list of (T, 22, 3)
    positions = line_positions(len(DANCE_VALUES), LINE_SPACING)      # (10, 3)

    # Colors: turbo colormap indexed by dance intensity 0.09 → 1.00
    cmap = plt.get_cmap("turbo")
    norm_vals = np.array(DANCE_VALUES)
    norm_vals = (norm_vals - norm_vals.min()) / (norm_vals.max() - norm_vals.min())
    colors = [cmap(0.15 + 0.75 * v) for v in norm_vals]   # avoid extreme ends

    # Figure setup — hi-res, dark, no chrome
    fig_w, fig_h = args.width / args.dpi, args.height / args.dpi
    fig = plt.figure(figsize=(fig_w, fig_h), dpi=args.dpi, facecolor="#0a0a12")
    ax = fig.add_subplot(111, projection="3d", facecolor="#0f0f18")
    fig.subplots_adjust(left=0, right=1, bottom=0, top=1)

    # Compute view bounds from all frames + positions
    all_positions = np.stack([m + p[None] for m, p in zip(motions, positions)])   # (10, T, 22, 3)
    mins = all_positions.reshape(-1, 3).min(axis=0)
    maxs = all_positions.reshape(-1, 3).max(axis=0)
    span = float(np.max(maxs - mins))
    center = (mins + maxs) / 2
    radius = span * 0.55

    build_background(ax, radius)

    def set_camera(frame: int):
        """Slow orbit ~30° over the piece, with subtle dolly-in."""
        t = frame / (NUM_FRAMES - 1)          # 0 → 1
        azim = -75 + 30 * t                    # slow orbit
        elev = 12 + 3 * np.sin(t * np.pi)      # gentle rise+fall
        ax.view_init(elev=elev, azim=azim)
        ax.set_xlim(center[0] - radius, center[0] + radius)
        ax.set_ylim(center[1] - radius, center[1] + radius)
        ax.set_zlim(center[2] - radius * 0.6, center[2] + radius * 1.1)
        ax.set_box_aspect((1, 1, 1))

    def draw_frame(frame: int):
        ax.cla()
        build_background(ax, radius)
        set_camera(frame)

        for motion, pos, color in zip(motions, positions, colors):
            # Motion-blur trail — draw last N frames faintly first
            for k, alpha in enumerate(TRAIL_ALPHAS):
                f = frame - (TRAIL_LENGTH - k)
                if f >= 0:
                    render_character(ax, motion[f], pos, color, alpha=alpha, linewidth=1.4)
            # Main character on top
            render_character(ax, motion[frame], pos, color, alpha=0.95, linewidth=2.0)

        # Title overlay — subtle, floats in space
        if frame < 20:
            title_alpha = frame / 20 * 0.6
        elif frame > NUM_FRAMES - 30:
            title_alpha = max(0, (NUM_FRAMES - frame) / 30) * 0.6
        else:
            title_alpha = 0.6
        ax.text2D(
            0.02, 0.95, "S P E C T R U M   C H O R U S", transform=ax.transAxes,
            color="#e8e6ff", alpha=title_alpha, fontsize=22, weight="light",
            family="serif",
        )
        ax.text2D(
            0.02, 0.92, "identity preservation across a learned spectrum",
            transform=ax.transAxes, color="#8b8aa8", alpha=title_alpha * 0.7,
            fontsize=11, style="italic", family="serif",
        )

    print(f"[chorus] rendering {NUM_FRAMES} frames at {args.width}x{args.height} @ {args.fps}fps")
    ani = FuncAnimation(fig, draw_frame, frames=NUM_FRAMES, interval=1000 / args.fps, blit=False)
    writer = FFMpegWriter(fps=args.fps, bitrate=6000, codec="libx264",
                          extra_args=["-pix_fmt", "yuv420p", "-crf", "18"])
    ani.save(str(out_path), writer=writer, dpi=args.dpi,
             savefig_kwargs={"facecolor": "#0a0a12"})
    plt.close(fig)
    print(f"[done] saved: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
