"""
Run all edit_t2m.py jobs for both tuned and pretrained models,
then produce a blind A/B quad comparison video.

Quad layout (same for both models):
  TL: Tags + Text  |  TR: Text Only
  BL: Tags Only    |  BR: Steps (10% increments)

Usage:
    python scripts/run_and_compare.py
    python scripts/run_and_compare.py --skip_inference   # skip edit_t2m, just make videos
"""

import argparse
import random
import re
import subprocess
import sys
import tempfile
from pathlib import Path

# ---------------------------------------------------------------------------
# Mode-based intensity steps (from spectrum score distribution analysis)
# These match the actual folder names generated by the inference commands.
# ---------------------------------------------------------------------------
STEPS = [
    {'dance': 0.09, 'walk': 0.91, 'tail': 'A person walks forward.'},
    {'dance': 0.11, 'walk': 0.91, 'tail': 'A person walks forward.'},
    {'dance': 0.28, 'walk': 0.91, 'tail': 'A person dances with a walking base.'},
    {'dance': 0.39, 'walk': 0.91, 'tail': 'A person dances with a walking base.'},
    {'dance': 0.40, 'walk': 0.91, 'tail': 'A person dances with a walking base.'},
    {'dance': 0.51, 'walk': 0.91, 'tail': 'A person dances with a walking base.'},
    {'dance': 0.63, 'walk': 0.91, 'tail': 'A person dances with a walking base.'},
    {'dance': 0.74, 'walk': 0.91, 'tail': 'A person dances with a walking base.'},
    {'dance': 0.80, 'walk': 0.91, 'tail': 'A person dances expressively.'},
    {'dance': 1.00, 'walk': 0.91, 'tail': 'A person dances expressively.'},
]

TUNED_MASK  = 'MaskTransformer'
TUNED_RES   = 'ResTransformer'
PRE_MASK    = 't2m_nlayer8_nhead6_ld384_ff1024_cdp0.1_rvq6ns'
PRE_RES     = 'tres_nlayer8_ld384_ff1024_rvq6ns_cdp0.2_sw'

SOURCE      = 'momask_input.npz'
MASK_SEC    = '0.0,1.0'

PANEL_LABELS = {
    'tl': 'Tags+Text',
    'tr': 'Text Only',
    'bl': 'Tags Only',
    'br': 'Steps',
}

# ---------------------------------------------------------------------------
# Folder maps — match actual output folder names from inference commands.
#
# Tuned model:
#   TL  dance_mode_{d}          [dance:d][walk:0.91] + sentence
#   TR  no-tag_{d}              sentence only (no tags)
#   BL  no-txt_dance_mode_{d}   [dance:d][walk:0.91] (no sentence)
#   BR  tuned_steps_{pct}       10% even steps [dance:0.10]...[dance:1.00]
#
# Pretrained model: same layout, prefixed with pretrained_
# ---------------------------------------------------------------------------
TUNED_FOLDERS = {
    'tl': lambda d: f'dance_mode_{d}',
    'tr': lambda d: f'no-tag_{d}',
    'bl': lambda d: f'no-txt_dance_mode_{d}',
}

# Map each mode-percentile step to its nearest tuned_steps_* folder
TUNED_STEPS_MAP = {
    '0.09': 'tuned_steps_0.10', '0.11': 'tuned_steps_0.10',
    '0.28': 'tuned_steps_0.30', '0.39': 'tuned_steps_0.40',
    '0.40': 'tuned_steps_0.40', '0.51': 'tuned_steps_0.50',
    '0.63': 'tuned_steps_0.60', '0.74': 'tuned_steps_0.70',
    '0.80': 'tuned_steps_0.80', '1.00': 'tuned_steps_1.00',
}

PRE_FOLDERS = {
    'tl': lambda d: f'pretrained_tags_text_{d}',
    'tr': lambda d: f'pretrained_text_only_{d}',
    'bl': lambda d: f'pretrained_tags_only_{d}',
}

PRE_STEPS_MAP = {
    '0.09': 'pretrained_steps_0.10', '0.11': 'pretrained_steps_0.10',
    '0.28': 'pretrained_steps_0.30', '0.39': 'pretrained_steps_0.40',
    '0.40': 'pretrained_steps_0.40', '0.51': 'pretrained_steps_0.50',
    '0.63': 'pretrained_steps_0.60', '0.74': 'pretrained_steps_0.70',
    '0.80': 'pretrained_steps_0.80', '1.00': 'pretrained_steps_1.00',
}


# ---------------------------------------------------------------------------
# Inference
# ---------------------------------------------------------------------------

def build_jobs(model_prefix, mask_name, res_name):
    """Return list of (ext, prompt) for one model.
    Folder names match TUNED_FOLDERS / PRE_FOLDERS conventions.
    """
    jobs = []
    for s in STEPS:
        d   = f"{s['dance']:.2f}"
        w   = f"{s['walk']:.2f}"
        tag = f"[dance:{d}][walk:{w}]"

        if model_prefix == 'tuned':
            jobs.append((f'dance_mode_{d}',         f"{tag} {s['tail']}"))
            jobs.append((f'no-tag_{d}',              s['tail']))
            jobs.append((f'no-txt_dance_mode_{d}',   tag))
        else:
            jobs.append((f'pretrained_tags_text_{d}',  f"{tag} {s['tail']}"))
            jobs.append((f'pretrained_text_only_{d}',  s['tail']))
            jobs.append((f'pretrained_tags_only_{d}',  tag))

    return jobs, mask_name, res_name


def run_inference(jobs, mask_name, res_name):
    for ext, prompt in jobs:
        cmd = [
            sys.executable, 'edit_t2m.py',
            '--gpu_id', '0',
            '--ext', ext,
            '--name', mask_name,
            '--dataset_name', 't2m',
            '--res_name', res_name,
            '--text_prompt', prompt,
            '--source_motion', SOURCE,
            '--mask_edit_section', MASK_SEC,
            '--use_res_model',
            '--repeat_times', '1',
        ]
        print(f'  Running: {ext}')
        subprocess.run(cmd, check=True)


# ---------------------------------------------------------------------------
# Video helpers
# ---------------------------------------------------------------------------

def ffmpeg(*args, check=True):
    result = subprocess.run(
        ['ffmpeg', '-y', '-loglevel', 'warning'] + list(args),
        capture_output=True, text=True
    )
    if check and result.returncode != 0:
        raise subprocess.CalledProcessError(result.returncode, result.args,
                                            result.stdout, result.stderr)
    return result


def find_first_repeat(folder: Path):
    anim = folder / 'animations' / '0'
    if not anim.exists():
        return None
    cands = sorted(p for p in anim.glob('*.mp4')
                   if '_source_' not in p.name and '_ik.' not in p.name)
    return cands[0] if cands else None


def add_label(src: Path, label: str, dance_val: str, uid: str, tmp_dir: str) -> Path:
    """Burn label onto video. Falls back to plain copy if drawtext is unavailable."""
    out = Path(tmp_dir) / f'{uid}_labeled.mp4'
    safe_text = label.replace(':', '\\:').replace("'", "\\'")
    result = ffmpeg(
        '-i', str(src),
        '-vf', f"drawtext=text='{safe_text} d={dance_val}':fontsize=16:"
               f"fontcolor=white:x=10:y=10:box=1:boxcolor=black@0.6:boxborderw=4",
        '-c:v', 'libx264', '-preset', 'fast', '-crf', '22', '-an', str(out),
        check=False
    )
    if result.returncode != 0:
        # drawtext failed (e.g. missing fontconfig) — just re-encode without label
        print(f'    [warn] drawtext unavailable, copying without label: {label} d={dance_val}')
        ffmpeg('-i', str(src), '-c:v', 'libx264', '-preset', 'fast', '-crf', '22',
               '-an', str(out))
    return out


def scale_video(src: Path, w: int, h: int, uid: str, tmp_dir: str) -> Path:
    out = Path(tmp_dir) / f'{uid}_scaled.mp4'
    ffmpeg(
        '-i', str(src),
        '-vf', f'scale={w}:{h}:force_original_aspect_ratio=decrease,'
               f'pad={w}:{h}:(ow-iw)/2:(oh-ih)/2',
        '-c:v', 'libx264', '-preset', 'fast', '-crf', '22', '-an', str(out)
    )
    return out


def make_quad(tl, tr, bl, br, uid, tmp_dir) -> Path:
    top = Path(tmp_dir) / f'{uid}_top.mp4'
    bot = Path(tmp_dir) / f'{uid}_bot.mp4'
    out = Path(tmp_dir) / f'{uid}_quad.mp4'
    ffmpeg('-i', str(tl), '-i', str(tr),
           '-filter_complex', '[0:v][1:v]hstack=inputs=2[v]',
           '-map', '[v]', '-c:v', 'libx264', '-preset', 'fast', '-crf', '22', str(top))
    ffmpeg('-i', str(bl), '-i', str(br),
           '-filter_complex', '[0:v][1:v]hstack=inputs=2[v]',
           '-map', '[v]', '-c:v', 'libx264', '-preset', 'fast', '-crf', '22', str(bot))
    ffmpeg('-i', str(top), '-i', str(bot),
           '-filter_complex', '[0:v][1:v]vstack=inputs=2[v]',
           '-map', '[v]', '-c:v', 'libx264', '-preset', 'fast', '-crf', '22', str(out))
    return out


def concat_clips(clips, out: Path, tmp_dir: str):
    if not clips:
        raise RuntimeError(f'No clips to concatenate for {out}')
    list_file = Path(tmp_dir) / f'{out.stem}_list.txt'
    list_file.write_text('\n'.join(f"file '{str(p).replace(chr(92), '/')}'" for p in clips))
    ffmpeg('-f', 'concat', '-safe', '0', '-i', str(list_file),
           '-c:v', 'libx264', '-preset', 'fast', '-crf', '22', str(out))


def build_quad_video(editing_dir: Path, folder_map: dict, steps_map: dict,
                     model_tag: str, pw: int, ph: int, tmp_dir: str) -> Path:
    """
    TL: tags+text  |  TR: text only
    BL: tags only  |  BR: spectrum steps (nearest 10% bin)
    """
    clips = []
    for s in STEPS:
        d = f"{s['dance']:.2f}"

        paths = {pos: editing_dir / folder_map[pos](d) for pos in ('tl', 'tr', 'bl')}
        paths['br'] = editing_dir / steps_map[d]
        videos = {pos: find_first_repeat(p) for pos, p in paths.items()}

        if any(v is None for v in videos.values()):
            missing = [pos for pos, v in videos.items() if v is None]
            print(f'  Skipping dance={d} — missing: {missing}')
            for pos, p in paths.items():
                print(f'    {pos}: {p}  exists={p.exists()}')
            continue

        print(f'  Compositing dance={d}')
        try:
            panels = {}
            for pos, vid in videos.items():
                uid = f'{model_tag}_{pos}_{d}'
                labeled = add_label(vid, PANEL_LABELS[pos], d, uid + '_lbl', tmp_dir)
                panels[pos] = scale_video(labeled, pw, ph, uid + '_sc', tmp_dir)

            quad = make_quad(panels['tl'], panels['tr'],
                             panels['bl'], panels['br'],
                             f'{model_tag}_d{d}', tmp_dir)
            clips.append(quad)
        except Exception as e:
            print(f'  [error] dance={d} failed: {e} — skipping')

    out = Path(tmp_dir) / f'{model_tag}_full.mp4'
    concat_clips(clips, out, tmp_dir)
    return out


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--editing_dir', default='editing')
    parser.add_argument('--out_dir', default='blind_review')
    parser.add_argument('--panel_w', type=int, default=480)
    parser.add_argument('--panel_h', type=int, default=360)
    parser.add_argument('--skip_inference', action='store_true',
                        help='Skip edit_t2m.py runs, go straight to video assembly')
    args = parser.parse_args()

    editing_dir = Path(args.editing_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # --- Inference ---
    if not args.skip_inference:
        print('=== Running fine-tuned model inference ===')
        tuned_jobs, tm, tr = build_jobs('tuned', TUNED_MASK, TUNED_RES)
        run_inference(tuned_jobs, tm, tr)

        print('\n=== Running pretrained model inference ===')
        pre_jobs, pm, pr = build_jobs('pretrained', PRE_MASK, PRE_RES)
        run_inference(pre_jobs, pm, pr)

    # --- Video assembly ---
    print('\n=== Building quad videos ===')
    with tempfile.TemporaryDirectory() as tmp_dir:
        print('Building tuned model quad...')
        tuned_vid = build_quad_video(editing_dir, TUNED_FOLDERS, TUNED_STEPS_MAP,
                                     'tuned', args.panel_w, args.panel_h, tmp_dir)

        print('Building pretrained model quad...')
        pre_vid = build_quad_video(editing_dir, PRE_FOLDERS, PRE_STEPS_MAP,
                                   'pre', args.panel_w, args.panel_h, tmp_dir)

        # Random A/B assignment
        if random.random() < 0.5:
            a_src, b_src = tuned_vid, pre_vid
            a_name, b_name = 'fine-tuned', 'pretrained'
        else:
            a_src, b_src = pre_vid, tuned_vid
            a_name, b_name = 'pretrained', 'fine-tuned'

        import shutil
        shutil.copy(str(a_src), str(out_dir / 'A.mp4'))
        shutil.copy(str(b_src), str(out_dir / 'B.mp4'))

    key_path = out_dir / 'key.txt'
    key_path.write_text(
        f"Blind Comparison Key\n"
        f"====================\n"
        f"A = {a_name} model\n"
        f"B = {b_name} model\n\n"
        f"Quad layout:\n"
        f"  Top-left:     Tags + Text\n"
        f"  Top-right:    Text Only\n"
        f"  Bottom-left:  Tags Only\n"
        f"  Bottom-right: 10% Steps\n"
    )

    print(f'\nDone.')
    print(f'  {out_dir}/A.mp4  =  {a_name}')
    print(f'  {out_dir}/B.mp4  =  {b_name}')
    print(f'  Key saved to {key_path} (open after reviewing)')


if __name__ == '__main__':
    main()
